"""Build sim/data/classes.json from rules/classes/*.md and metadata/abilities.json.

Equipment and Look The Part come from each class file; abilities per level come from the
availability rows in metadata/abilities.json (themselves extracted from the same class files).
Every field records the file it came from. Re-run after the rulebook or metadata changes:

    .venv/bin/python -m sim.rules.build_classes
"""
from __future__ import annotations

import json
import re
import sys

from sim.paths import ABILITIES_JSON, CLASSES_DIR, CLASSES_JSON, REPO
from sim.rules import frequency

CLASS_FILES = {
    "Anti-Paladin": "anti-paladin.md", "Archer": "archer.md", "Assassin": "assassin.md",
    "Barbarian": "barbarian.md", "Bard": "bard.md", "Druid": "druid.md", "Healer": "healer.md",
    "Monk": "monk.md", "Paladin": "paladin.md", "Scout": "scout.md", "Warrior": "warrior.md",
    "Wizard": "wizard.md",
}
SHIELD_SIZES = {"none": "none", "small": "small", "medium": "medium", "large": "large"}


def _rel(path) -> str:
    return str(path.relative_to(REPO))


def _field(text: str, name: str) -> str | None:
    m = re.search(rf"^\s*-?\s*\*\*{name}:\*\*\s*(.*)$", text, re.M)
    return m.group(1).strip() if m else None


def _magic_users() -> tuple[list[str], str]:
    path = CLASSES_DIR / "_overview.md"
    m = re.search(r"\*\*Magic Users:\*\*\s*(.+?)\.", path.read_text())
    names = [n.strip() for n in re.split(r",\s*(?:and\s+)?|\s+and\s+", m.group(1)) if n.strip()]
    return names, _rel(path)


def _look_the_part(text: str, slugs: dict[str, str]) -> dict:
    raw = _field(text, "Look The Part")
    if raw is None:
        return {"kind": "none", "options": []}
    if "magic point" in raw.lower():
        return {"kind": "magic-point", "points": 1, "raw": raw, "options": []}
    lines = [raw]
    if raw.lower().startswith("pick one:") and raw.lower().strip() == "pick one:":
        block = text.split("**Look The Part:**", 1)[1].splitlines()[1:]
        lines = [ln.strip()[2:] for ln in block if ln.strip().startswith("- ")][:4]
    elif raw.lower().startswith("pick one ability:"):
        names, freq = raw.split(":", 1)[1].split(";")
        lines = [f"{n.strip()} {freq.strip()}" for n in names.split(",")]
    options = []
    for ln in lines:
        name = next((n for n in sorted(slugs, key=len, reverse=True) if ln.lower().startswith(n.lower())), None)
        if name is None:
            continue
        rest = ln[len(name):].strip().lstrip("-").strip()
        options.append({"slug": slugs[name], "frequency": frequency.parse(rest).to_dict()})
    return {"kind": "pick-one" if len(options) > 1 else "ability", "raw": raw, "options": options}


def _kind(av: dict, record: dict) -> str:
    src = av["source"]
    if src == "Spell table":
        return "spell"
    if src == "Level table":
        return "level"
    if src.startswith("Look The Part"):
        return "look-the-part"
    if record["delivery"] == "archetype":
        return "archetype"
    if av.get("cost"):
        return "spell"          # purchasable equipment rows for Magic Users
    return "granted"            # appears only through an Archetype or another ability


def build() -> dict:
    data = json.loads(ABILITIES_JSON.read_text())
    records = data["abilities"]
    records = list(records.values()) if isinstance(records, dict) else records
    slugs = {r["title"]: r["slug"] for r in records}
    magic_users, mu_src = _magic_users()
    out: dict = {"_about": "Generated by sim/rules/build_classes.py from rules/classes/*.md and "
                           "metadata/abilities.json. Lives are a battlegame setting in V8.08 "
                           "(rules/battlegames.md), not a class property, so they live in scenarios.",
                 "classes": {}}
    for cls, fname in CLASS_FILES.items():
        path = CLASSES_DIR / fname
        text = path.read_text()
        src = _rel(path)
        armor_raw = _field(text, "Armor") or "None"
        armor = int(m.group(1)) if (m := re.match(r"(\d+)", armor_raw)) else 0
        shield_raw = (_field(text, "Shields") or "None").strip()
        weapons_raw = _field(text, "Weapons") or ""
        abilities = []
        for r in records:
            for av in r["availability"]:
                if av["cls"] != cls:
                    continue
                kind = _kind(av, r)
                if kind == "look-the-part":
                    continue
                trait = kind == "level" and bool(re.search(rf"{re.escape(r['title'])} \(T\)", text))
                abilities.append({
                    "slug": r["slug"], "name": r["title"], "kind": kind, "trait": trait,
                    "levels": av["levels"], "frequency": frequency.parse(av["frequency"]["raw"]).to_dict(),
                    "cost": int(av["cost"]) if str(av.get("cost") or "").isdigit() else None,
                    "max": int(av["max"]) if str(av.get("max") or "").isdigit() else None,
                    "range": av.get("range") or r.get("range") or "",
                    "option": av.get("option") or "", "tag": av.get("tag") or "",
                    "source": f"{src} ({av['source']})",
                })
        abilities.sort(key=lambda a: (min(a["levels"] or [0]), a["name"]))
        out["classes"][cls] = {
            "name": cls,
            "source": src,
            "magic_user": {"value": cls in magic_users, "source": mu_src},
            "armor": {"value": armor, "raw": armor_raw, "source": f"{src} (Equipment)"},
            "shield": {"value": SHIELD_SIZES.get(shield_raw.lower(), "none"), "raw": shield_raw,
                       "source": f"{src} (Equipment)"},
            "weapons": {"value": [w.strip() for w in weapons_raw.split(",") if w.strip()],
                        "source": f"{src} (Equipment)"},
            "look_the_part": {**_look_the_part(text, slugs), "source": f"{src} (Look The Part)"},
            "abilities": abilities,
        }
    return out


def main() -> int:
    out = build()
    CLASSES_JSON.write_text(json.dumps(out, indent=1) + "\n")
    n = sum(len(c["abilities"]) for c in out["classes"].values())
    print(f"wrote {CLASSES_JSON.relative_to(REPO)}: {len(out['classes'])} classes, {n} ability rows")
    return 0


if __name__ == "__main__":
    sys.exit(main())
