"""Effect-kind coverage: which metadata effects the engine executes and which are logged no-ops.

    .venv/bin/python -m sim.rules.coverage          # prints a summary and writes sim/COVERAGE.md
"""
from __future__ import annotations

import sys
from collections import Counter, defaultdict

from sim.engine.effects import handling
from sim.paths import SIM
from sim.rules.compile import default_rules


def compute(rules=None) -> dict:
    rules = rules or default_rules()
    in_classes = {ca.slug for c in rules.classes.values() for ca in c.abilities}
    names = set(rules.by_name)
    kinds: dict[str, dict] = defaultdict(lambda: {"abilities": set(), "instances": 0, "modes": Counter()})
    per_ability = {}
    for ab in rules.abilities.values():
        modes = []
        for eff in ab.effects:
            mode = handling(ab, eff, names)
            k = kinds[eff.kind]
            k["abilities"].add(ab.slug)
            k["instances"] += 1
            k["modes"][mode] += 1
            modes.append(mode)
        if not modes:
            status = "no effects"
        elif all(m != "no-op" for m in modes):
            status = "full"
        elif any(m != "no-op" for m in modes):
            status = "partial"
        else:
            status = "none"
        per_ability[ab.slug] = {"status": status, "handled": sum(m != "no-op" for m in modes),
                                "effects": len(modes), "in_class_sheets": ab.slug in in_classes}
    return {"kinds": dict(kinds), "abilities": per_ability}


def render(cov: dict) -> str:
    kinds, abil = cov["kinds"], cov["abilities"]
    total_inst = sum(k["instances"] for k in kinds.values())
    handled_inst = sum(k["instances"] - k["modes"]["no-op"] for k in kinds.values())
    status = Counter(a["status"] for a in abil.values())
    lines = [
        "# Simulator effect coverage",
        "",
        "Generated by `sim/rules/coverage.py` from `metadata/abilities.json` and `sim/engine/effects.py`.",
        "An effect is **instant** (run when the ability resolves), **passive** (a worn Enchantment/Trait",
        "the engine queries), **loadout** (an Archetype/Trait change applied when the player is built),",
        "or a **no-op** (counted in the `noop` metric of every run, never silently dropped).",
        "",
        f"- Effect instances handled: **{handled_inst} of {total_inst}** ({handled_inst / total_inst:.0%})",
        f"- Abilities fully handled: **{status['full']}**, partly: **{status['partial']}**, "
        f"not at all: **{status['none']}**, no effects recorded: {status['no effects']} "
        f"(of {len(abil)})",
        "",
        "## By effect kind",
        "",
        "| Kind | Abilities | Instances | Handled | Mode |",
        "| --- | ---: | ---: | ---: | --- |",
    ]
    for kind, k in sorted(kinds.items(), key=lambda kv: (-len(kv[1]["abilities"]), kv[0])):
        handled = k["instances"] - k["modes"]["no-op"]
        mode = ", ".join(f"{m} {n}" for m, n in sorted(k["modes"].items()))
        lines.append(f"| `{kind}` | {len(k['abilities'])} | {k['instances']} | {handled} | {mode} |")
    lines += ["", "## Abilities with no handled effects", ""]
    none = sorted(s for s, a in abil.items() if a["status"] == "none")
    lines.append(", ".join(f"`{s}`" for s in none) if none else "None.")
    lines += ["", "## Abilities partly handled", ""]
    part = sorted((s, a) for s, a in abil.items() if a["status"] == "partial")
    lines.append(", ".join(f"`{s}` ({a['handled']}/{a['effects']})" for s, a in part) if part else "None.")
    return "\n".join(lines) + "\n"


def main() -> int:
    cov = compute()
    text = render(cov)
    (SIM / "COVERAGE.md").write_text(text)
    print("\n".join(text.splitlines()[7:10]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
