"""Effect-kind coverage: which metadata effects the engine executes, which are explicitly not
modeled in Phase 1 (needs-map / out-of-scope, each with a reason), and which are logged no-ops.

    .venv/bin/python -m sim.rules.coverage          # prints a summary and writes sim/COVERAGE.md
"""
from __future__ import annotations

import sys
from collections import Counter, defaultdict

from sim.engine.effects import NEEDS_MAP, OUT_OF_SCOPE, handling, unmodeled
from sim.paths import SIM
from sim.rules.compile import default_rules

UNMODELED_MODES = (NEEDS_MAP, OUT_OF_SCOPE)
NOT_HANDLED = ("no-op",) + UNMODELED_MODES


def compute(rules=None) -> dict:
    rules = rules or default_rules()
    in_classes = {ca.slug for c in rules.classes.values() for ca in c.abilities}
    names = set(rules.by_name)
    kinds: dict[str, dict] = defaultdict(lambda: {"abilities": set(), "instances": 0, "modes": Counter()})
    per_ability = {}
    reasons: dict[tuple[str, str], dict] = {}
    for ab in rules.abilities.values():
        modes = []
        for eff in ab.effects:
            mode = handling(ab, eff, names)
            k = kinds[eff.kind]
            k["abilities"].add(ab.slug)
            k["instances"] += 1
            k["modes"][mode] += 1
            modes.append(mode)
            if mode in UNMODELED_MODES:
                _, reason = unmodeled(ab, eff)
                r = reasons.setdefault((mode, reason), {"kinds": set(), "effects": []})
                r["kinds"].add(eff.kind)
                r["effects"].append(f"{ab.slug} {eff.id}")
        if not modes:
            status = "no effects"
        elif all(m not in NOT_HANDLED for m in modes):
            status = "full"
        elif any(m not in NOT_HANDLED for m in modes):
            status = "partial"
        else:
            status = "none"
        per_ability[ab.slug] = {"status": status, "handled": sum(m not in NOT_HANDLED for m in modes),
                                "effects": len(modes), "noop": sum(m == "no-op" for m in modes),
                                "unmodeled": sum(m in UNMODELED_MODES for m in modes),
                                "in_class_sheets": ab.slug in in_classes}
    return {"kinds": dict(kinds), "abilities": per_ability, "reasons": reasons}


def totals(cov: dict) -> dict:
    kinds = cov["kinds"]
    out = {"instances": sum(k["instances"] for k in kinds.values())}
    for m in NOT_HANDLED:
        out[m] = sum(k["modes"][m] for k in kinds.values())
    out["handled"] = out["instances"] - sum(out[m] for m in NOT_HANDLED)
    return out


def render(cov: dict) -> str:
    kinds, abil = cov["kinds"], cov["abilities"]
    tot = totals(cov)
    status = Counter(a["status"] for a in abil.values())
    lines = [
        "# Simulator effect coverage",
        "",
        "Generated by `sim/rules/coverage.py` from `metadata/abilities.json` and `sim/engine/effects.py`.",
        "An effect is **instant** (run when the ability resolves), **passive** (a worn Enchantment/Trait",
        "the engine queries), **loadout** (an Archetype/Trait change applied when the player is built),",
        "**needs-map** or **out-of-scope** (explicitly not modeled in Phase 1, with the reason below), or a",
        "**no-op** (not handled yet). Unmodeled and no-op effects are counted in the `noop` metric of every",
        "run (unmodeled ones under the detail `<mode>:<kind>`); nothing is silently dropped.",
        "",
        f"- Effect instances handled: **{tot['handled']} of {tot['instances']}** ({tot['handled'] / tot['instances']:.0%})",
        f"- Not handled: **{tot['no-op']}** no-op, **{tot[NEEDS_MAP]}** needs-map, **{tot[OUT_OF_SCOPE]}** out-of-scope",
        f"- Abilities fully handled: **{status['full']}**, partly: **{status['partial']}**, "
        f"not at all: **{status['none']}**, no effects recorded: {status['no effects']} "
        f"(of {len(abil)})",
        "",
        "## By effect kind",
        "",
        "| Kind | Abilities | Instances | Handled | Mode |",
        "| --- | ---: | ---: | ---: | --- |",
    ]
    for kind, k in sorted(kinds.items(), key=lambda kv: (-len(kv[1]["abilities"]), kv[0])):
        handled = k["instances"] - sum(k["modes"][m] for m in NOT_HANDLED)
        mode = ", ".join(f"{m} {n}" for m, n in sorted(k["modes"].items()))
        lines.append(f"| `{kind}` | {len(k['abilities'])} | {k['instances']} | {handled} | {mode} |")
    lines += ["", "## Not modeled in Phase 1", "",
              "| Mode | Kinds | Effects | Reason |", "| --- | --- | --- | --- |"]
    for (mode, reason), r in sorted(cov["reasons"].items(), key=lambda kv: (kv[0][0], sorted(kv[1]["kinds"]), kv[0][1])):
        ks = ", ".join(f"`{k}`" for k in sorted(r["kinds"]))
        effs = ", ".join(sorted(r["effects"]))
        lines.append(f"| {mode} | {ks} | {effs} | {reason} |")
    lines += ["", "## Abilities with no handled effects", ""]
    none = sorted(s for s, a in abil.items() if a["status"] == "none")
    lines.append(", ".join(f"`{s}`" for s in none) if none else "None.")
    lines += ["", "## Abilities partly handled", "",
              "Counts are handled/total; `u` marks how many of the rest are explicitly not modeled.", ""]
    part = sorted((s, a) for s, a in abil.items() if a["status"] == "partial")

    def cell(s: str, a: dict) -> str:
        extra = f", {a['unmodeled']}u" if a["unmodeled"] else ""
        return f"`{s}` ({a['handled']}/{a['effects']}{extra})"

    lines.append(", ".join(cell(s, a) for s, a in part) if part else "None.")
    return "\n".join(lines) + "\n"


def main() -> int:
    cov = compute()
    text = render(cov)
    (SIM / "COVERAGE.md").write_text(text)
    print("\n".join(text.splitlines()[9:13]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
